# M1A2 - Manipulação de arrays com NumPy

Nessa aula iremos aprender como manipular matriz e vetores utilizando [NumPY](https://numpy.org/)

Esse notebook está estruturado da seguinte forma.

- Instalação
- Operações básicas com vetores
- Operaçõões básicas com matrizes
- Próximos passos
- Atividade Complementares

## Instalação e Importação da Biblioteca

In [26]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [27]:
import numpy as np

## Operações Básicas com Vetores

Primeiro vamos criar vetores para que possamos entender como eles são representados, e como podemos manipular eles. 

Nesse exemplos, vamos utilizar os vetores $\vec{u}$ e $\vec{v}$ com coordenadas $(1, 3)$ e $(3, 1)$ respectivamente como ilustrado na imagem abaixo.

![vetores u e v](vetores.png)

In [28]:
# Criando vetores.
u = np.array([1, 3])
v = np.array([3, 1])

Operações feitas individualmente nas dimensões do vetores como substração e adição podem ser feitas utilizando os operadores $-$ e $+$.

In [29]:
y = u - v
w = u + v

print(f"Vetor y: {y}\nVetor w: {w}")

Vetor y: [-2  2]
Vetor w: [4 4]


Analogamente podemos visualizar esses resultados no plano cartesiano.

![subtração e adição com u e v](sub-add-vecs.png)

Multiplicação e divisão são feitas elemento por elemento.

Com essa multiplicação podemos realizar o produto escalar, por exemplo $\alpha * \vec{u}$

In [30]:
a = u / v
b = u * v

print(f"Vetor a: {a}\nVetor b: {b}")

alpha = 2
escalar = alpha * u
print(f"Produtor escalar de u por alpha: {escalar}")

Vetor a: [0.33333333 3.        ]
Vetor b: [3 3]
Produtor escalar de u por alpha: [2 6]


Também é possível realizar operações geométrica como produto interno e vetorial.

In [31]:
interno = np.dot(u, v)


# Para o produto vetorial iremos utilizar vetores tridimensionais.
u3 = np.array([1, 3, 1])
v3 = np.array([3, 1, 1])
vetorial = np.cross(u3, v3)

print(f"Resultado produto interno: {interno}\nResutlado produto vetorial: {vetorial}")

Resultado produto interno: 6
Resutlado produto vetorial: [ 2  2 -8]


## Operações Básicas com Matrizes

A primeira coisa a compreender é como representar matrizes. Analogamente a vetores, em NumPy matrizes são vetores bidimesionais.

Vamos fazer alguns exemplos e observar que podemos reproduzir todas as operações.

In [32]:
I = np.array([[1, 0],[0, 1]])
A = np.array([[2, 1],[1, 2]])

De maneira semelhante quando utilizamos vetores as operações podem ser realizadas elemento a elemento, ou seguindo a algebra que estamos familiarizados.

In [33]:
B = A + I

print(f"Matriz A:\n{A}\n\nMatriz Identidade:\n{I}\n\nMatriz B = A + I:\n{B}")

Matriz A:
[[2 1]
 [1 2]]

Matriz Identidade:
[[1 0]
 [0 1]]

Matriz B = A + I:
[[3 1]
 [1 3]]


In [34]:
B = A - I

print(f"Matriz A:\n{A}\n\nMatriz Identidade:\n{I}\n\nMatriz B = A - I:\n{B}")

Matriz A:
[[2 1]
 [1 2]]

Matriz Identidade:
[[1 0]
 [0 1]]

Matriz B = A - I:
[[1 1]
 [1 1]]


Os operadores não precisam nem ter exatamente as mesmas dimensões.

In [35]:
C = A + u

print(f"Matriz A:\n{A}\nVetor u:\n{u}\n\nMatriz C = A + u:\n{C}")

Matriz A:
[[2 1]
 [1 2]]
Vetor u:
[1 3]

Matriz C = A + u:
[[3 4]
 [2 5]]


Para realizarmos a multiplicação de matrizes também podemos utilizar NumPy. Desde que observe-se a regra de colunas e linhas compatíveis entre os operadores.

In [36]:
D = np.matmul(A, I)

print(f"Matriz A:\n{A}\n\nMatriz Identidade:\n{I}\n\nMatriz D = A x I:\n{D}")

Matriz A:
[[2 1]
 [1 2]]

Matriz Identidade:
[[1 0]
 [0 1]]

Matriz D = A x I:
[[2 1]
 [1 2]]


## Próximos Passos e Referências

Nas próximas aulas iremos compreender como essa estrutura de dados e operações fornecidas pela biblioteca NumPy são funcionais para os problemas comuns em Visão Computacional.

Uma lista não exaustiva de referências segue:

- https://numpy.org/devdocs/user/absolute_beginners.html
- https://www.geogebra.org/
- https://numpy.org/devdocs/user/whatisnumpy.html
- https://numpy.org/devdocs/user/quickstart.html

## Atividades Complementares (Opicional)

Faça operações com outras matrizes.

- [ ] Existe outra forma de instaciar matrizes e vetores especiais (matriz identidade, vetor nulo, etc)?
- [ ] Existe outra forma de realizar as operações que chamamos da biblioteca (np.dot, np.matmul)?
- [ ] É possível trabalhar com arrays multi-dimensionais? Faça alguns testes com vetores e matrizes 3D.

### Atividade 1: Outras formas de instanciar matrizes e vetores especiais

In [ ]:


# Vetor nulo
zero_vec = np.zeros(3)
print(f"Vetor nulo: {zero_vec}")

# Vetor de uns
ones_vec = np.ones(3)
print(f"Vetor de uns: {ones_vec}")

# Matriz identidade(alternativa a np.array([[1,0],[0,1]]))
I_eye = np.eye(3)
print(f"\nMatriz identidade 3x3 (np.eye):\n{I_eye}")

# Matriz de zeros e de uns
zeros_mat = np.zeros((3, 3))
ones_mat = np.ones((3, 3))
print(f"\nMatriz de zeros:\n{zeros_mat}")
print(f"\nMatriz de uns:\n{ones_mat}")

# Matriz diagonal personalizada
diag_mat = np.diag([1, 2, 3])
print(f"\nMatriz diagonal com [1,2,3]:\n{diag_mat}")

# Vetor com valores igualmente espaçados
linspace_vec = np.linspace(0, 1, 5)
print(f"\nVetor linspace(0,1,5): {linspace_vec}")

# Vetor com range
arange_vec = np.arange(0, 10, 2)
print(f"Vetor arange(0,10,2): {arange_vec}")

Vetor nulo: [0. 0. 0.]
Vetor de uns: [1. 1. 1.]

Matriz identidade 3x3 (np.eye):
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Matriz de zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Matriz de uns:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Matriz diagonal com [1,2,3]:
[[1 0 0]
 [0 2 0]
 [0 0 3]]

Vetor linspace(0,1,5): [0.   0.25 0.5  0.75 1.  ]
Vetor arange(0,10,2): [0 2 4 6 8]


### Atividade 2: Outras formas de realizar np.dot e np.matmul

In [ ]:
u = np.array([1, 3])
v = np.array([3, 1])
A = np.array([[2, 1], [1, 2]])
I = np.eye(2)

# Produto interno — 3 formas equivalentes
print("=== Produto Interno ===")
print(f"np.dot(u, v)      = {np.dot(u, v)}")
print(f"u @ v             = {u @ v}")
print(f"np.inner(u, v)    = {np.inner(u, v)}")

# Multiplicação de matrizes — 3 formas equivalentes
print("\n=== Multiplicação de Matrizes ===")
print(f"np.matmul(A, I):\n{np.matmul(A, I)}")
print(f"A @ I:\n{A @ I}")                    
print(f"np.dot(A, I):\n{np.dot(A, I)}")      

# Produto externo (outer product)
outer = np.outer(u, v)
print(f"\nProduto externo (np.outer):\n{outer}")

=== Produto Interno ===
np.dot(u, v)      = 6
u @ v             = 6
np.inner(u, v)    = 6

=== Multiplicação de Matrizes ===
np.matmul(A, I):
[[2. 1.]
 [1. 2.]]
A @ I:
[[2. 1.]
 [1. 2.]]
np.dot(A, I):
[[2. 1.]
 [1. 2.]]

Produto externo (np.outer):
[[3 1]
 [9 3]]


### Atividade 3: Arrays multidimensionais — vetores e matrizes 3D

In [41]:

# Vetor 3D
u3 = np.array([1, 2, 3])
v3 = np.array([4, 5, 6])

print("=== Vetores 3D ===")
print(f"u3 = {u3}  |  shape: {u3.shape}")
print(f"u3 + v3 = {u3 + v3}")
print(f"u3 · v3 (dot) = {np.dot(u3, v3)}")
print(f"u3 × v3 (cross) = {np.cross(u3, v3)}")
print(f"norma de u3 = {np.linalg.norm(u3):.4f}")

# Matriz 3x3
A3 = np.array([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]])

print("\n=== Matriz 3x3 ===")
print(f"A3:\n{A3}")
print(f"shape: {A3.shape}  |  ndim: {A3.ndim}")
print(f"Transposta:\n{A3.T}")
print(f"Trace (soma diagonal): {np.trace(A3)}")
print(f"Determinante: {np.linalg.det(A3):.4f}")

# Tensor 3D (ex: batch de 2 matrizes 3x3 — comum em visão computacional)
tensor = np.zeros((2, 3, 3))
tensor[0] = A3
tensor[1] = A3.T

print("\n=== Tensor 3D (shape 2x3x3) ===")
print(f"shape: {tensor.shape}  |  ndim: {tensor.ndim}")
print(f"tensor[0] (A3):\n{tensor[0]}")
print(f"tensor[1] (A3.T):\n{tensor[1]}")

# Multiplicação em lote com einsum
batch_result = np.einsum('bij,bjk->bik', tensor, tensor)
print(f"\nProduto A3 @ A3 via einsum:\n{batch_result[0]}")

=== Vetores 3D ===
u3 = [1 2 3]  |  shape: (3,)
u3 + v3 = [5 7 9]
u3 · v3 (dot) = 32
u3 × v3 (cross) = [-3  6 -3]
norma de u3 = 3.7417

=== Matriz 3x3 ===
A3:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
shape: (3, 3)  |  ndim: 2
Transposta:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Trace (soma diagonal): 15
Determinante: -0.0000

=== Tensor 3D (shape 2x3x3) ===
shape: (2, 3, 3)  |  ndim: 3
tensor[0] (A3):
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
tensor[1] (A3.T):
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]

Produto A3 @ A3 via einsum:
[[ 30.  36.  42.]
 [ 66.  81.  96.]
 [102. 126. 150.]]
